---
- name: Playbook to configure AAP
  hosts: localhost
  gather_facts: false
 
  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars

  tasks:
    !
    !
    - name: Import role-aap-object-job-template
      ansible.builtin.include_role:
        name: role-aap-object-job-template
      vars:
        build: true
        name: "{{ item.value.job_template_name }}"
        playbook: "{{ item.value.playbook }}"
        credentials: "{{ credentials }}"
        execution_environment: "{{ item.value.execution_environment }}"
        instance_groups: "{{ instance_groups }}"
        job_type: "{{ job_type }}"
        description: "{{ common_description }}"
        organization: "{{ organization }}"
        inventory: "{{ inventory_name }}"
        project: "{{ project_name }}"
        state: "{{ state }}"
      loop: "{{ lookup('dict', templates) }}"  
    !
    !