---
# Create job templates
- name: "Build job templates - {{ name }}"
  ansible.controller.job_template:
    name: "{{ name }}"
    playbook: "{{ playbook }}"
    credentials: "{{ credentials }}"
    execution_environment: "{{ execution_environment }}"
    timeout: "{{ timeout }}"
    instance_groups: "{{ instance_groups }}"
    job_type: "{{ job_type }}"
    description: "{{ description }}"
    organization: "{{ organization }}"
    inventory: "{{ inventory }}"
    project: "{{ project }}"
    state: "{{ state }}"