---
# Create job templates
- name: "Build {{ in_list[0] }} job templates"
  ansible.controller.job_template:
    name: "{{ in_list[0] }}"
    job_type: "run"
    description: "{{ common_description }}"
    organization: "{{ organization_name }}"
    inventory: "{{ inventory_name }}"
    project: "{{ project_name }}"
    playbook: "{{ in_list[1] }}"
    credentials: 
      - "{{ in_list[2] }}"
      - "{{ network_credential_name }}"
    state: "present"
    execution_environment: "{{ in_list[3] }}" # Temporary until exec node can pull down images 
    timeout: "{{ job_template_timeout }}"
    instance_groups: "{{ exec_nodes_instance_groups }}"
